### PR TITLE
Install development version of R Shinylive

### PR DESCRIPTION
**Pull request by georgestagg**
Hi,

Apologies for the delay in getting back to you about Shinylive. The latest version of the R Shinylive package should fix the deployment issues you were seeing. The latest version isn't on CRAN yet, but this PR will tweak things so that the development version is used to deploy your Shinylive app.

GHA log: https://github.com/georgestagg/tima-shinylive/actions/runs/11438858245/job/31825093316
Result: https://georgestagg.github.io/tima-shinylive/

### CODE REVIEW

**Comment by Adafede** [comment]
Hi @georgestagg and thank you so much for this good news!

I tried it and got the following error:

Screenshot 2024-10-21 at 15 58 31


Already went further than last time! 😊

**Comment by georgestagg** [comment]
Ah yes, you're right. The previous issues have been solved, but there is another.

It looks like you are using the `{targets}` system in your app, this is not yet supported with Shinylive because it uses `{callr}` by default which does not work under webR.

It might be possible to make it work by running targets with an additional argument to avoid using `{callr}` when running under Emscripten, along the lines of the below, but I expect other issues will occur.

```r
if (R.Version()$os == "emscripten") {
  tar_make(callr_function = NULL)`
} else {
  tar_make()
}
```

I'll return to this when I can and continue to experiment. This seems to be a very complex app, I hope we're able to get it up and running for you eventually!

**Comment by Adafede** [comment]
I probably need to make the example files available by a simple button to ease such investigations...The app itself shouldn't be as complicated as it unncessarily is (this is to improve on my side 😞 )

**Comment by Adafede** [comment]
> Ah yes, you're right. The previous issues have been solved, but there is another.
> 
> It looks like you are using the `{targets}` system in your app, this is not yet supported with Shinylive because it uses `{callr}` by default which does not work under webR.
> 
> It might be possible to make it work by running targets with an additional argument to avoid using `{callr}` when running under Emscripten, along the lines of the below, but I expect other issues will occur.
> 
> ```r
> if (R.Version()$os == "emscripten") {
>   tar_make(callr_function = NULL)`
> } else {
>   tar_make()
> }
> ```
> 
> I'll return to this when I can and continue to experiment. This seems to be a very complex app, I hope we're able to get it up and running for you eventually!

@wlandau Any guidance regarding the above?

**Comment by georgestagg** [comment]
> I probably need to make the example files available by a simple button to ease such investigations

I have example files now. I just discovered `tima::get_example_files()`, which was very useful.

> The app itself shouldn't be as complicated as it unncessarily is (this is to improve on my side 😞 )

To be clear: this is a shortcoming in the webR system, not your app or in the `targets` package. Ideally we'd like to be able to handle arbitrarily complex applications, but we're still working on building support for all R package dependencies for WebAssembly.

It will be a long time before we can run every R package in Shinylive, but we're slowly increasing compatibility over time and I hope to get close to there one day.

I'll convert this to a draft PR for now...

**Comment by wlandau** [comment]
> @wlandau Any guidance regarding the above?

`call_function = NULL` can be a reasonable workaround for some apps, depending on how sensitive your pipeline is to in-memory dependencies in the global environment.

**Comment by Adafede** [comment]
@georgestagg I am curious to see the next steps after this is merged so I'll merge and feel free to re-open anytime 👍🏼

**Comment by Adafede** [comment]
@georgestagg I tried building multiple times since I merged and keep on having failures because of dependencies conflicts that do not seem to occur on your fork...I don't understand why

**Comment by georgestagg** [comment]
Ah, I'm not sure why the behaviour is different but I see that there's new versions of `igraph` and `gt` on CRAN not compiled for the https://repo.r-wasm.org binary repository yet.

These two packages are from a small selection of packages that currently must be manually patched for WebAssembly. I'll just quickly update them...

I have pushed the updates to the repo, please try building again now.

**Comment by Adafede** [comment]
@georgestagg Thank you for the prompt answer!

I just tried again and those two are gone but colorspace and BiocVersion issues remain still: https://github.com/taxonomicallyinformedannotation/tima-shinylive/actions/runs/11555641658/job/32161530214#step:5:354

In the future, any hints on how to prevent these?

**Comment by georgestagg** [comment]
> @georgestagg Thank you for the prompt answer!

No problem, this has been an interesting app to investigate and I'm now personally interested in seeing it all work 😅

> I just tried again and those two are gone but colorspace and BiocVersion issues remain still:

OK. It is hard for me to debug since I can't reproduce on my fork(!), but it might just be that those packages are not installed in the container and so Shinylive does not know how to export them... maybe.

You could try changing the following line in the workflow:

https://github.com/taxonomicallyinformedannotation/tima-shinylive/blob/d917b6a71ff06d9a736878c2a3f54736552a4b35/.github/workflows/deploy-app.yaml#L44

to also install those packages:

```r
install.packages(c("tima", "colourspace", "BiocVersion"), repos = c("https://taxonomicallyinformedannotation.r-universe.dev", "https://bioc.r-universe.dev", "https://r-lib.r-universe.dev", "https://cloud.r-project.org"), dependencies = TRUE)
```

**Comment by Adafede** [comment]
Oh...well actually I remember previously adding a lot of dependencies that caused the failures to the `tima-r-universe` (https://github.com/taxonomicallyinformedannotation/taxonomicallyinformedannotation.r-universe.dev/blob/main/packages.json) to solve the issue, would you recommend putting those there too?

**Comment by georgestagg** [comment]
No, I don't think you need to also include them there if you include "https://bioc.r-universe.dev" in the list in the `repos` in `install.packages()`, as we are doing above. Sorry if I have said in the past that you needed to add them, I have only just recently discovered the `bioc` R-Universe mirror myself...

What what I understand about how all this fits together, you should only need to include the packages that are not already on CRAN or BioConductor in your own R-Universe list.

**Comment by Adafede** [comment]
I really don't get it... I tried removing the ones already on `bioc-universe`, but possibly because their dependencies are not listed correctly, then it fails even worse (see https://github.com/taxonomicallyinformedannotation/tima-shinylive/actions/runs/11556924815/job/32165742079#step:4:2585).
I now added them back again, and added the additional `colorspace` and `BiocVersion` dependencies in https://github.com/taxonomicallyinformedannotation/tima-shinylive/commit/a833b309756cc17a276f777c0f4d47d406650d90 as you suggested...let's see 😊

**Comment by georgestagg** [comment]
I'm really sorry, but I don't get it either 🙁 I tried pulling your latest commits in my fork and it still does work[1]. But AFAICT there should now be no difference between our repos. I'll return to this in a few days and see if I can figure things out.

[1] https://github.com/georgestagg/tima-shinylive/actions/runs/11557542680/job/32167803679

**Comment by Adafede** [comment]
Oh, it installed now but there is the next error:

https://github.com/taxonomicallyinformedannotation/tima-shinylive/actions/runs/11558395582/job/32170661427#step:5:1 😵

**Pull request merged**
